/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public static void main(String[] args) {

        Macaco m = new Macaco("Chico");
        System.out.println(m.habilidade());
    }
}
