/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {


        ArrayList<String> nomes = new ArrayList<>();
        ArrayList<Pessoa> agenda = new ArrayList<>();
        nomes.add("POO");
        Pessoa chico = new Pessoa("Chico Linguisa", "franciscotoscana@gmail.com");

        nomes.add("EST");
        nomes.add("ICO");
        nomes.add("FDM");
        agenda.add(new Pessoa("Blum","vitinho@gmail.com"));
        agenda.add(new Pessoa("LG" ,"elege@gmail.com"));
        agenda.add(new Pessoa("Motora", "ilovemotos@gmail.com"));

        for (String elemento : nomes){
            System.out.println(elemento);
        }

        for (Pessoa elemento : agenda){
            System.out.println(elemento.toString());
        }

        nomes.forEach(elemento-> System.out.println(elemento));
        agenda.forEach(System.out::println);

        nomes.removeIf(elemento-> elemento.equals("POO"));
        nomes.forEach(System.out::println);

        agenda.removeIf(elemento-> elemento.getNome().equals("Motora"));
        agenda.forEach(System.out::println);









    }
}

