/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.ArrayList;
import java.util.List;

public class App {
    public static void main(String[] args) {

        List<Funcionario> funcionarios = new ArrayList<>();

        MensalFixo mensalFixo = new MensalFixo(5000, "Vendedor", "João");
        Horista horista = new Horista(5000, "Vendedor", "Lula");
        Comissionado comissionado = new Comissionado(5000, "Vendedor", "Paula", 10);
        ComissionadoEfeito ComissionadoEfeito = new ComissionadoEfeito(5000, "Vendedor", "Vendedor Sênior", 15);

        funcionarios.add(mensalFixo);
        funcionarios.add(horista);
        funcionarios.add(comissionado);
        funcionarios.add(ComissionadoEfeito);


        System.out.println("Folha de Pagamento:");
        for (Funcionario funcionario : funcionarios) {
            System.out.println("Nome: " + funcionario.nome);
            System.out.println("Carreira: " + funcionario.cargo);
            System.out.println("Salário: " + funcionario.calcularSalario());
            System.out.println("----------------------");
        }

        System.out.println("Aumentando salário dos comissionados efetivos...");
        for (Funcionario funcionario : funcionarios) {
            if (funcionario instanceof ComissionadoEfeito) {
                ComissionadoEfeito ce = (ComissionadoEfeito) funcionario;
                ce.salarioBase *= 1.1; // Aumenta 10%
            }
        }

        System.out.println("Folha de Pagamento (Após Aumento):");
        for (Funcionario funcionario : funcionarios) {
            System.out.println("Nome: " + funcionario.nome);
            System.out.println("Carreira: " + funcionario.cargo);
            System.out.println("Salário: " + funcionario.calcularSalario());
            System.out.println("----------------------");
        }
    }
}