/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static final String SEG = "seg";
    public static final String TER = "ter";
    public static final String QUA = "qua";
    public static final String QUI = "qui";
    public static final String SEX = "sex";

    public static void main(String[] args) {

        Disciplina d = new Disciplina("POO", new DiasDaSemana[]{DiasDaSemana.SEGUNDA, DiasDaSemana.QUINTA});


        for (DiasDaSemana a : DiasDaSemana.values()){
            System.out.println(d);
        }

        DiasDaSemana e = DiasDaSemana.TERCA;

        switch (e){
            case SEGUNDA -> System.out.println("Tem aula :( ");
            case TERCA -> System.out.println("nÃO TEM AULA :) ");
        }

        Planetas pp = Planetas.SATURNO;

        for (Planetas p : Planetas.values()) {
            System.out.println(p);
        }

    }
}
