/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {

        Linha l = new Linha(new Ponto(10.2, 10.2), new Ponto(20.0, 20.0), "Azul");

        System.out.println(l.desenhar());
    }
}
